export const BOTAO_CLICADO_SUCCESS = 'BOTAO_CLICBOTAO_CLICADO_SUCCESSADO';
export const BOTAO_CLICADO_REQUEST = 'BOTAO_CLICBOTAO_CLICADO_REQUEST';
export const BOTAO_CLICADO_FAILURE = 'BOTAO_CLICBOTAO_CLICADO_FAILURE';
